//! Primary interface for high-level interactions with the screen.
// if someone has better descriptions for these @ me

pub mod transition;
pub mod widget;

/// Helper macro to generate bitmap chaaracters, for use with the display and
/// [`WidgetContent::CustomCharacter`](`crate::ui::widget::WidgetContent::CustomCharacter`).
///
/// # Usage
/// ```rust
/// let heart: [u8; 8] = bitmap!(
///    (. . . . .),
///    (. # . # .),
///    (# # # # #),
///    (# # # # #),
///    (. # # # .),
///    (. . # . .),
///    (. . . . .),
///    (. . . . .),
/// );
/// assert_eq!(heart, [
///    0b00000, // 0x0
///    0b01010, // 0xA
///    0b11111, // 0x1F
///    0b11111, // 0x1F
///    0b01110, // 0xE
///    0b00100, // 0x4
///    0b00000, // 0x0
///    0b00000, // 0x0
/// ]);
/// ```
///
/// DISCLAIMER: This macro is generated by an LLM. Claude Sonnet 4.6, specifically.
/// If you do not wish to use AI generated code, you can just declare a bitmap with an `u8` array.
///
/// Outside of this macro, this project contains no AI generated code.
#[macro_export]
macro_rules! bitmap {
    ($(($($bit:tt)+)),+ $(,)?) => {
        [$({ $crate::bitmap!(@row 0u8; $($bit)+) }),+]
    };

    (@row $($bit:tt)*) => {
        $crate::bitmap!(@acc $($bit)*)
    };

    (@acc $acc:expr;) => { $acc };
    (@acc $acc:expr; . $($rest:tt)*) => {
        $crate::bitmap!(@acc ($acc << 1); $($rest)*)
    };
    (@acc $acc:expr; # $($rest:tt)*) => {
        $crate::bitmap!(@acc ($acc << 1) | 1; $($rest)*)
    };
}

use crate::{
    ScreenCoordinates,
    backend::{BackendError, LcdBackend},
    error::{StorageError, UiError},
    storage::{QueueContainer, SetContainer, StackContainer, Storage, TextContainer},
    ui::{
        transition::Transition,
        widget::{CustomCharacterRef, Widget, WidgetContent},
    },
};
use core::fmt::Debug;
// for some reason this needs to be here, even though .round() needs it
#[allow(unused_imports)]
use num_traits::float::FloatCore;

#[cfg(feature = "log")]
use log::{debug, error};

#[cfg(feature = "async")]
use crate::backend::AsyncLcdBackend;

use embedded_hal::delay::DelayNs as Delay;
#[cfg(feature = "async")]
use embedded_hal_async::delay::DelayNs as ADelay;

type IdWidget<S> = (u32, Widget<S>);

#[derive(Debug)]
struct ScreenMetadata<const CHAR_HEIGHT: usize, S: Storage> {
    widgets: S::Vec<IdWidget<S>>,
    last_frame_drawn: S::Set<ScreenCoordinates>,
    registered_custom_chars: S::Vec<(u32, [u8; CHAR_HEIGHT])>,
}
impl<const CHAR_HEIGHT: usize, S: Storage> Default for ScreenMetadata<CHAR_HEIGHT, S> {
    fn default() -> Self {
        Self {
            widgets: Default::default(),
            last_frame_drawn: Default::default(),
            registered_custom_chars: Default::default(),
        }
    }
}

struct LcdScreenCore<const CHAR_HEIGHT: usize, S: Storage> {
    meta: ScreenMetadata<CHAR_HEIGHT, S>,
    required_custom_chars: Result<S::Vec<CustomCharacterRef>, S::Vec<CustomCharacterRef>>,
    id_counter: u32,
}

impl<const CHAR_HEIGHT: usize, S: Storage> LcdScreenCore<CHAR_HEIGHT, S> {
    fn advance_id(&mut self) -> u32 {
        let id = self.id_counter;
        self.id_counter = self.id_counter.wrapping_add(1);
        id
    }

    fn new_elem(
        &mut self,
        content: WidgetContent<S::Text>,
        pos: ScreenCoordinates,
        hidden: bool,
    ) -> Result<u32, StorageError> {
        let id = self.advance_id();
        let screen_state = &mut self.meta;
        screen_state.widgets.push((
            id,
            Widget {
                content,
                pos,
                hidden,
                transitions: S::Queue::new(),
                transition_progress: None,
            },
        ))?;
        self.update_required_custom_chars();
        Ok(id)
    }

    fn register_custom_char(
        &mut self,
        bitmap: [u8; CHAR_HEIGHT],
    ) -> Result<CustomCharacterRef, StorageError> {
        let id = self.advance_id();
        self.meta.registered_custom_chars.push((id, bitmap))?;
        Ok(CustomCharacterRef(id))
    }
    fn unregister_custom_char(
        &mut self,
        character: CustomCharacterRef,
    ) -> Option<[u8; CHAR_HEIGHT]> {
        let char = self
            .meta
            .registered_custom_chars
            .iter()
            .enumerate()
            .find(|(_, (id, _))| *id == character.0);
        if let Some((idx, (_, elem))) = char {
            let ret = Some(*elem);
            self.meta.registered_custom_chars.remove(idx);
            ret
        } else {
            None
        }
    }
    fn reregister_custom_char(
        &mut self,
        character: CustomCharacterRef,
        new_bitmap: [u8; CHAR_HEIGHT],
    ) {
        let char = self
            .meta
            .registered_custom_chars
            .iter_mut()
            .enumerate()
            .find(|(_, (id, _))| *id == character.0);
        if let Some((_, (_, old_bitmap))) = char {
            *old_bitmap = new_bitmap;
        }
    }

    fn queue_transition(
        &mut self,
        key: u32,
        transition: Transition<S::Text>,
    ) -> Result<(), StorageError> {
        let found = self.meta.widgets.iter_mut().find(|(id, _)| *id == key);
        if let Some((_, elem)) = found {
            elem.transitions.enqueue(transition)?;
        } else {
            #[cfg(feature = "log")]
            error!("no elem with id {key}")
        }
        Ok(())
    }

    fn tick(&mut self) {
        let mut needs_update = false;
        self.meta.widgets = self.meta.widgets
            .drain_all()
            .filter_map(|(id, mut elem)| {
                match elem.transitions.peek_mut() {
                    Some(Transition::Delete) => {
                        needs_update |= matches!(elem.content, WidgetContent::CustomCharacter(_));
                        None
                    },
                    rest => {
                        match rest {
                            Some(Transition::Hide) => {
                                elem.hidden = true;
                                elem.transitions.dequeue();
                                needs_update |= matches!(elem.content, WidgetContent::CustomCharacter(_));
                            },
                            Some(Transition::Show) => {
                                elem.hidden = false;
                                elem.transitions.dequeue();
                                needs_update |= matches!(elem.content, WidgetContent::CustomCharacter(_));
                            },
                            Some(Transition::ChangeTo(new)) => {
                                #[cfg(feature = "log")]
                                debug!("Transitioning {:?} into {new:?}", elem.content);
                                needs_update |= matches!(new, WidgetContent::CustomCharacter(_));
                                needs_update |= matches!(elem.content, WidgetContent::CustomCharacter(_));
                                core::mem::swap(&mut elem.content, new);
                                elem.transitions.dequeue();
                            }
                            Some(old_trans @ &mut Transition::MoveTo { new, duration }) => {
                                let old = elem.pos;
                                _ = elem.transition_progress.insert(1);
                                #[cfg(feature = "log")]
                                debug!("Resolving move transition to {new:?}");
                                let mut new_trans= Transition::MoveToExt { old, new, duration };
                                core::mem::swap(old_trans, &mut new_trans);
                            }
                            Some(&mut Transition::MoveToExt { old, new, duration }) => {
                                let progress = elem.transition_progress.get_or_insert(0);
                                #[cfg(feature = "log")]
                                debug!(
                                    "Transitioning from {old:?} to {new:?}, {progress}/{duration} ticks passed"
                                );
                                let t = *progress as f32 / duration as f32;
                                let lerped_pos = (
                                    (old.x() as f32 + (new.x() as f32 - old.x() as f32) * t).round() as u8,
                                    (old.y() as f32 + (new.y() as f32 - old.y() as f32) * t).round() as u8,
                                );
                                elem.pos = lerped_pos.into();
                                if *progress < duration {
                                    *progress += 1;
                                } else {
                                    elem.transition_progress = None;
                                    elem.transitions.dequeue();
                                }
                            }
                            Some(&mut Transition::Wait { duration }) => {
                                let progress = elem.transition_progress.get_or_insert(0);
                                if *progress < duration {
                                    *progress += 1;
                                } else {
                                    elem.transition_progress = None;
                                    elem.transitions.dequeue();
                                }
                            }
                            _ => (),
                        }
                        Some((id, elem))
                    }
                }
            })
            .collect();
        if needs_update {
            self.update_required_custom_chars();
        }
    }

    fn update_required_custom_chars(&mut self) {
        let mut used = S::Vec::new();
        let mut full = false;
        for (_, widget) in self.meta.widgets.iter() {
            if let WidgetContent::CustomCharacter(id) = widget.content
                && !widget.hidden
            {
                full |= used.push(id).is_err();
            }
        }

        self.required_custom_chars = if full { Err(used) } else { Ok(used) }
    }

    fn bitmap_of(&self, char: CustomCharacterRef) -> Option<[u8; CHAR_HEIGHT]> {
        self.meta
            .registered_custom_chars
            .iter()
            .find(|(r, _)| *r == char.0)
            .map(|(_, ch)| *ch)
    }
}

/// The manager for all UI widgets. Blocking version.
///
/// ### Generics
/// - `CHAR_HEIGHT`: How tall (in screen pixels) are each character. This is also the length of all
///   custom bitmap arrays.
/// - `CUSTOM_CHARACTER_SLOTS`: How many custom character slots the screen hardware supports.
/// - `S`: The storage adapter. Implements [`Storage`](`crate::storage::Storage`).
/// - `D`: The display backend. Implements [`LcdScreen`](`crate::backend::LcdBackend`).
/// - `Y`: A delay struct implementing [`DelayNs`](`embedded_hal::delay::DelayNs`).
pub struct LcdScreen<
    const CHAR_HEIGHT: usize,
    const CUSTOM_CHARACTER_SLOTS: usize,
    S: Storage,
    D: LcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>,
    Y: Delay,
> {
    core: LcdScreenCore<CHAR_HEIGHT, S>,
    screen_custom_chars: [Option<u32>; CUSTOM_CHARACTER_SLOTS], // idx -> screen character slot, u32 -> character id
    lcd: D,
    delay: Y,
}

/// The manager for all UI widgets. Async version.
///
/// ### Generics
/// - `CHAR_HEIGHT`: How tall (in screen pixels) are each character. This is also the length of all
///   custom bitmap arrays.
/// - `CUSTOM_CHARACTER_SLOTS`: How many custom character slots the screen hardware supports.
/// - `S`: The storage adapter. Implements [`Storage`](`crate::storage::Storage`).
/// - `D`: The display backend. Implements [`LcdScreen`](`crate::backend::LcdBackend`).
/// - `Y`: A delay struct implementing [`DelayNs`](`embedded_hal_async::delay::DelayNs`).
#[cfg(feature = "async")]
pub struct AsyncLcdScreen<
    const CHAR_HEIGHT: usize,
    const CUSTOM_CHARACTER_SLOTS: usize,
    S: Storage,
    D: AsyncLcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>,
    Y: ADelay,
> {
    core: LcdScreenCore<CHAR_HEIGHT, S>,
    screen_custom_chars: [Option<u32>; CUSTOM_CHARACTER_SLOTS], // idx -> screen character slot, u32 -> character id
    lcd: D,
    delay: Y,
}

impl<
    const CHAR_HEIGHT: usize,
    const CUSTOM_CHARACTER_SLOTS: usize,
    S: Storage,
    D: LcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>,
    Y: Delay,
> LcdScreen<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS, S, D, Y>
{
    /// Initializes the screen UI.
    pub fn new(mut lcd: D, mut delay: Y) -> Result<Self, UiError<D::Error>> {
        let delay_mut = &mut delay;
        lcd.prepare_screen(delay_mut)?.clear(delay_mut)?;

        Ok(LcdScreen {
            core: LcdScreenCore {
                meta: ScreenMetadata::default(),
                required_custom_chars: Ok(S::Vec::default()),
                id_counter: 0,
            },
            screen_custom_chars: [None; CUSTOM_CHARACTER_SLOTS],
            lcd,
            delay,
        })
    }

    fn addr_of_character(&self, id: u32) -> Option<u8> {
        self.screen_custom_chars
            .iter()
            .enumerate()
            .find(|(_, i)| i.is_some_and(|i| i == id))
            .map(|(idx, _)| idx as u8)
    }

    /// Creates a new widget on the screen.
    pub fn new_elem(
        &mut self,
        content: WidgetContent<S::Text>,
        pos: impl Into<ScreenCoordinates>,
        hidden: bool,
    ) -> Result<u32, UiError<D::Error>> {
        Ok(self.core.new_elem(content, pos.into(), hidden)?)
    }

    /// Registers a custom character for use with the screen.
    pub fn register_custom_char(
        &mut self,
        bitmap: [u8; CHAR_HEIGHT],
    ) -> Result<CustomCharacterRef, UiError<D::Error>> {
        Ok(self.core.register_custom_char(bitmap)?)
    }
    /// Removes a registration of a custom character.
    pub fn unregister_custom_char(
        &mut self,
        character: CustomCharacterRef,
    ) -> Option<[u8; CHAR_HEIGHT]> {
        if let Some(idx) = self.addr_of_character(character.0) {
            _ = self.screen_custom_chars[idx as usize].take();
        }
        self.core.unregister_custom_char(character)
    }
    /// Changes an existing custom character.
    pub fn reregister_custom_char(
        &mut self,
        character: CustomCharacterRef,
        new_bitmap: [u8; CHAR_HEIGHT],
    ) -> Result<(), UiError<D::Error>> {
        self.core.reregister_custom_char(character, new_bitmap);
        if let Some(idx) = self.addr_of_character(character.0) {
            self.lcd
                .set_custom_character_at(&mut self.delay, idx, new_bitmap)?;
        }
        Ok(())
    }

    /// Queues a transition to run on the widget with the key `key`. The transitions will run
    /// sequentially.
    pub fn queue_transition(
        &mut self,
        key: u32,
        transition: Transition<S::Text>,
    ) -> Result<&mut Self, UiError<D::Error>> {
        self.core.queue_transition(key, transition)?;
        Ok(self)
    }

    /// Ticks the UI and all of its widgets, then draws the current UI state to the screen.
    pub fn draw(&mut self) -> Result<(), UiError<D::Error>>
    where
        <D as LcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>>::Error: BackendError,
    {
        let mut ret = Ok(());

        self.core.tick();

        let needed_custom_chars = match &self.core.required_custom_chars {
            Ok(r) => r,
            Err(r) => {
                #[cfg(feature = "log")]
                error!("Not enough storage to store full list of custom characters!");
                ret = Err(UiError::Storage(StorageError::NotEnoughStorage));
                r
            }
        };
        for needed in needed_custom_chars.iter() {
            if !self.screen_custom_chars.contains(&Some(needed.0)) {
                let empty = self
                    .screen_custom_chars
                    .iter()
                    .position(|opt| opt.is_none());
                if let Some(idx) = empty
                    && let Some(bitmap) = self.core.bitmap_of(*needed)
                {
                    self.lcd
                        .set_custom_character_at(&mut self.delay, idx as u8, bitmap)?;
                    _ = self.screen_custom_chars[idx].insert(needed.0);
                } else {
                    #[cfg(feature = "log")]
                    error!("Not enough screen storage to store all needed custom characters!");
                    ret = Err(UiError::InsufficentCharacterStorage);
                }
            }
        }

        let mut drawn_this_frame = S::Vec::new();
        for (_, elem) in self.core.meta.widgets.iter() {
            if !elem.hidden {
                self.lcd.move_cursor(&mut self.delay, elem.pos)?;
                match &elem.content {
                    WidgetContent::Text(ascii_string) => {
                        self.lcd.write_str(&mut self.delay, ascii_string.chars())?;
                        drawn_this_frame.extend(
                            (elem.pos.x()..(elem.pos.x() + ascii_string.len() as u8))
                                .map(|x| ScreenCoordinates::at(x, elem.pos.y())),
                        );
                    }
                    WidgetContent::CustomCharacter(CustomCharacterRef(id)) => {
                        if let Some(idx) = self.addr_of_character(*id) {
                            self.lcd.write_custom_character(&mut self.delay, idx)?;
                            drawn_this_frame.push(elem.pos)?;
                        } else {
                            #[cfg(feature = "log")]
                            error!("No custom character with ID {id}!")
                        }
                    }
                }
            }
        }

        for pixel in self
            .core
            .meta
            .last_frame_drawn
            .iter()
            .filter(|&x| !drawn_this_frame.contains(x))
        {
            self.lcd
                .move_cursor(&mut self.delay, *pixel)?
                .write_byte(&mut self.delay, b' ')?;
        }

        self.core.meta.last_frame_drawn = {
            let mut s = S::Set::new();
            s.extend(drawn_this_frame);
            s
        };

        ret
    }
}

#[cfg(feature = "async")]
impl<
    const CHAR_HEIGHT: usize,
    const CUSTOM_CHARACTER_SLOTS: usize,
    S: Storage,
    D: AsyncLcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>,
    Y: ADelay,
> AsyncLcdScreen<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS, S, D, Y>
{
    /// Initializes the screen UI.
    pub async fn new(mut lcd: D, mut delay: Y) -> Result<Self, UiError<D::Error>> {
        lcd.prepare_screen(&mut delay)
            .await?
            .clear(&mut delay)
            .await?;

        Ok(AsyncLcdScreen {
            core: LcdScreenCore {
                meta: ScreenMetadata::default(),
                required_custom_chars: Ok(S::Vec::default()),
                id_counter: 0,
            },
            screen_custom_chars: [None; CUSTOM_CHARACTER_SLOTS],
            lcd,
            delay,
        })
    }

    fn addr_of_character(&self, id: u32) -> Option<u8> {
        self.screen_custom_chars
            .iter()
            .enumerate()
            .find(|(_, i)| i.is_some_and(|i| i == id))
            .map(|(idx, _)| idx as u8)
    }

    /// Creates a new widget on the screen.
    pub fn new_elem(
        &mut self,
        content: WidgetContent<S::Text>,
        pos: impl Into<ScreenCoordinates>,
        hidden: bool,
    ) -> Result<u32, UiError<D::Error>> {
        Ok(self.core.new_elem(content, pos.into(), hidden)?)
    }

    /// Registers a custom character for use with the screen.
    pub fn register_custom_char(
        &mut self,
        bitmap: [u8; CHAR_HEIGHT],
    ) -> Result<CustomCharacterRef, UiError<D::Error>> {
        Ok(self.core.register_custom_char(bitmap)?)
    }
    /// Removes a registration of a custom character.
    pub fn unregister_custom_char(
        &mut self,
        character: CustomCharacterRef,
    ) -> Option<[u8; CHAR_HEIGHT]> {
        if let Some(idx) = self.addr_of_character(character.0) {
            _ = self.screen_custom_chars[idx as usize].take();
        }
        self.core.unregister_custom_char(character)
    }
    /// Changes an existing custom character.
    pub async fn reregister_custom_char(
        &mut self,
        character: CustomCharacterRef,
        new_bitmap: [u8; CHAR_HEIGHT],
    ) -> Result<(), UiError<D::Error>> {
        self.core.reregister_custom_char(character, new_bitmap);
        if let Some(idx) = self.addr_of_character(character.0) {
            self.lcd
                .set_custom_character_at(&mut self.delay, idx, new_bitmap)
                .await?;
        }
        Ok(())
    }

    /// Queues a transition to run on the widget with the key `key`. The transitions will run
    /// sequentially.
    pub fn queue_transition(
        &mut self,
        key: u32,
        transition: Transition<S::Text>,
    ) -> Result<&mut Self, UiError<D::Error>> {
        self.core.queue_transition(key, transition)?;
        Ok(self)
    }

    /// Ticks the UI and all of its widgets, then draws the current UI state to the screen.
    pub async fn draw(&mut self) -> Result<(), UiError<D::Error>>
    where
        <D as AsyncLcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>>::Error: BackendError,
    {
        let mut ret = Ok(());

        self.core.tick();

        let needed_custom_chars = match &self.core.required_custom_chars {
            Ok(r) => r,
            Err(r) => {
                #[cfg(feature = "log")]
                error!("Not enough storage to store full list of custom characters!");
                ret = Err(UiError::InsufficentCharacterStorage);
                r
            }
        };
        for needed in needed_custom_chars.iter() {
            if !self.screen_custom_chars.contains(&Some(needed.0)) {
                let empty = self
                    .screen_custom_chars
                    .iter()
                    .position(|opt| opt.is_none());
                if let Some(idx) = empty
                    && let Some(bitmap) = self.core.bitmap_of(*needed)
                {
                    self.lcd
                        .set_custom_character_at(&mut self.delay, idx as u8, bitmap)
                        .await?;
                    _ = self.screen_custom_chars[idx].insert(needed.0);
                } else {
                    #[cfg(feature = "log")]
                    error!("Not enough screen storage to store all needed custom characters!");
                    ret = Err(UiError::InsufficentCharacterStorage);
                }
            }
        }

        let mut drawn_this_frame = S::Vec::new();
        for (_, elem) in self.core.meta.widgets.iter() {
            if !elem.hidden {
                self.lcd.move_cursor(&mut self.delay, elem.pos).await?;
                match &elem.content {
                    WidgetContent::Text(ascii_string) => {
                        self.lcd
                            .write_str(&mut self.delay, ascii_string.chars())
                            .await?;
                        drawn_this_frame.extend(
                            (elem.pos.x()..(elem.pos.x() + ascii_string.len() as u8))
                                .map(|x| ScreenCoordinates::at(x, elem.pos.y())),
                        );
                    }
                    WidgetContent::CustomCharacter(CustomCharacterRef(id)) => {
                        if let Some(idx) = self.addr_of_character(*id) {
                            self.lcd
                                .write_custom_character(&mut self.delay, idx)
                                .await?;
                            drawn_this_frame.push(elem.pos)?;
                        } else {
                            #[cfg(feature = "log")]
                            error!("No custom character with ID {id}!")
                        }
                    }
                }
            }
        }

        for pixel in self
            .core
            .meta
            .last_frame_drawn
            .iter()
            .filter(|&x| !drawn_this_frame.contains(x))
        {
            self.lcd
                .move_cursor(&mut self.delay, *pixel)
                .await?
                .write_byte(&mut self.delay, b' ')
                .await?;
        }

        self.core.meta.last_frame_drawn = {
            let mut s = S::Set::new();
            s.extend(drawn_this_frame);
            s
        };

        ret
    }
}
