//! Primary interface for high-level interactions with the screen.
// if someone has better descriptions for these @ me

pub mod transition;
pub mod widget;

/// Helper macro to generate bitmap chaaracters, for use with the display and
/// [`crate::ui::widget::WidgetContent::CustomCharacter`].
///
///
/// DISCLAIMER: This macro is generated by an LLM. Claude Sonnet 4.6, specifically.
/// If you do not wish to use AI generated code, you can just declare a bitmap with an `u8` array.
///
/// Outside of this macro, this project contains no AI generated code.
#[macro_export]
macro_rules! bitmap {
    ($(($($bit:tt)+)),+ $(,)?) => {
        [$({ $crate::bitmap!(@row 0u8; $($bit)+) }),+]
    };

    (@row $($bit:tt)*) => {
        $crate::bitmap!(@acc $($bit)*)
    };

    (@acc $acc:expr;) => { $acc };
    (@acc $acc:expr; . $($rest:tt)*) => {
        $crate::bitmap!(@acc ($acc << 1); $($rest)*)
    };
    (@acc $acc:expr; # $($rest:tt)*) => {
        $crate::bitmap!(@acc ($acc << 1) | 1; $($rest)*)
    };
}

// for some reason this needs to be here, even though .round() needs it
use core::fmt::Debug;
#[allow(unused_imports)]
use num_traits::float::FloatCore;

#[cfg(feature = "async")]
use log::{debug, error};

use crate::{
    ScreenCoordinates,
    backend::{BackendError, LcdBackend},
    error::{StorageError, UiError},
    storage::{QueueContainer, SetContainer, StackContainer, Storage, TextContainer},
    ui::{
        transition::Transition,
        widget::{CustomCharacterRef, Widget, WidgetContent},
    },
};

pub use embedded_hal::delay::DelayNs as Delay;
#[cfg(feature = "async")]
pub use embedded_hal_async::delay::DelayNs as ADelay;

type IdWidget<S> = (u32, Widget<S>);

#[derive(Debug)]
struct ScreenMetadata<const CUSTOM_CHARACTER_SLOTS: usize, S: Storage> {
    elems: S::Vec<IdWidget<S>>,
    last_frame_drawn: S::Set<ScreenCoordinates>,
    custom_characters: [Option<u32>; CUSTOM_CHARACTER_SLOTS], // idx -> screen character slot, u32 -> character id
}
impl<const CUSTOM_CHARACTER_SLOTS: usize, S: Storage> Default
    for ScreenMetadata<CUSTOM_CHARACTER_SLOTS, S>
{
    fn default() -> Self {
        Self {
            elems: Default::default(),
            last_frame_drawn: Default::default(),
            custom_characters: [None; CUSTOM_CHARACTER_SLOTS],
        }
    }
}

struct LcdScreenCore<const CHAR_HEIGHT: usize, const CUSTOM_CHARACTER_SLOTS: usize, S: Storage> {
    meta: ScreenMetadata<CUSTOM_CHARACTER_SLOTS, S>,
    id_counter: u32,
}

impl<const CHAR_HEIGHT: usize, const CUSTOM_CHARACTER_SLOTS: usize, S: Storage>
    LcdScreenCore<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS, S>
{
    fn advance_id(&mut self) -> u32 {
        let id = self.id_counter;
        self.id_counter = self.id_counter.wrapping_add(1);
        id
    }

    fn new_elem(
        &mut self,
        content: WidgetContent<S::Text>,
        pos: ScreenCoordinates,
        hidden: bool,
    ) -> Result<u32, StorageError> {
        let id = self.advance_id();
        let screen_state = &mut self.meta;
        screen_state.elems.push((
            id,
            Widget {
                content,
                pos,
                hidden,
                transitions: S::Queue::new(),
                transition_progress: None,
            },
        ))?;
        Ok(id)
    }

    fn free_slot_mut(&mut self) -> Option<(usize, &mut Option<u32>)> {
        self.meta
            .custom_characters
            .iter_mut()
            .enumerate()
            .find(|(_, x)| x.is_none())
    }
    fn find_slot_mut(
        &mut self,
        custom_char: CustomCharacterRef,
    ) -> Option<(usize, &mut Option<u32>)> {
        self.meta
            .custom_characters
            .iter_mut()
            .enumerate()
            .find(|(_, slot)| slot.is_some_and(|id| id == custom_char.0))
    }

    fn queue_transition(
        &mut self,
        key: u32,
        transition: Transition<S::Text>,
    ) -> Result<(), StorageError> {
        let found = self.meta.elems.iter_mut().find(|(id, _)| *id == key);
        if let Some((_, elem)) = found {
            elem.transitions.enqueue(transition)?;
        } else {
            #[cfg(feature = "log")]
            error!("no elem with id {key}")
        }
        Ok(())
    }

    fn tick(&mut self) {
        self.meta.elems = self.meta.elems
            .drain_all()
            .filter_map(|(id, mut elem)| {
                match elem.transitions.peek_mut() {
                    Some(Transition::Delete) => None,
                    rest => {
                        match rest {
                            Some(Transition::Hide) => {
                                elem.hidden = true;
                                elem.transitions.dequeue();
                            },
                            Some(Transition::Show) => {
                                elem.hidden = false;
                                elem.transitions.dequeue();
                            },
                            Some(Transition::ChangeTo(new)) => {
                                #[cfg(feature = "log")]
                                debug!("Transitioning {:?} into {new:?}", elem.content);
                                core::mem::swap(&mut elem.content, new);
                                elem.transitions.dequeue();
                            }
                            Some(old_trans@ &mut Transition::MoveTo { new, duration }) => {
                                let old = elem.pos;
                                _ = elem.transition_progress.insert(1);
                                #[cfg(feature = "log")]
                                debug!("Resolving move transition to {new:?}");
                                let mut new_trans= Transition::MoveToExt { old, new, duration };
                                core::mem::swap(old_trans, &mut new_trans);
                            }
                            Some(&mut Transition::MoveToExt { old, new, duration }) => {
                                let progress = elem.transition_progress.get_or_insert(0);
                                #[cfg(feature = "log")]
                                debug!(
                                    "Transitioning from {old:?} to {new:?}, {progress}/{duration} ticks passed"
                                );
                                let t = *progress as f32 / duration as f32;
                                let lerped_pos = (
                                    (old.x() as f32 + (new.x() as f32 - old.x() as f32) * t).round() as u8,
                                    (old.y() as f32 + (new.y() as f32 - old.y() as f32) * t).round() as u8,
                                );
                                elem.pos = lerped_pos.into();
                                if *progress < duration {
                                    *progress += 1;
                                } else {
                                    elem.transition_progress = None;
                                    elem.transitions.dequeue();
                                }
                            }
                            Some(&mut Transition::Wait { duration }) => {
                                let progress = elem.transition_progress.get_or_insert(0);
                                if *progress < duration {
                                    *progress += 1;
                                } else {
                                    elem.transition_progress = None;
                                    elem.transitions.dequeue();
                                }
                            }
                            _ => (),
                        }
                        Some((id, elem))
                    }
                }
            })
            .collect();
    }
}

/// The manager for all UI widgets. Blocking version.
pub struct LcdScreen<
    const CHAR_HEIGHT: usize,
    const CUSTOM_CHARACTER_SLOTS: usize,
    S: Storage,
    D: LcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>,
    Y: Delay,
> {
    core: LcdScreenCore<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS, S>,
    lcd: D,
    delay: Y,
}

/// The manager for all UI widgets. Async version.
#[cfg(feature = "async")]
pub struct AsyncLcdScreen<
    const CHAR_HEIGHT: usize,
    const CUSTOM_CHARACTER_SLOTS: usize,
    S: Storage,
    D: AsyncLcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>,
    Y: ADelay,
> {
    core: LcdScreenCore<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS, S>,
    lcd: D,
    delay: Y,
}

impl<
    const CHAR_HEIGHT: usize,
    const CUSTOM_CHARACTER_SLOTS: usize,
    S: Storage,
    D: LcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>,
    Y: Delay,
> LcdScreen<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS, S, D, Y>
{
    /// Initializes the screen UI.
    pub fn new(mut lcd: D, mut delay: Y) -> Result<Self, D::Error> {
        let delay_mut = &mut delay;
        lcd.prepare_screen(delay_mut)?.clear(delay_mut)?;

        Ok(LcdScreen {
            core: LcdScreenCore {
                meta: ScreenMetadata::default(),
                id_counter: 0,
            },
            lcd,
            delay,
        })
    }

    /// Creates a new widget on the screen.
    pub fn new_elem(
        &mut self,
        content: WidgetContent<S::Text>,
        pos: ScreenCoordinates,
        hidden: bool,
    ) -> Result<u32, StorageError> {
        self.core.new_elem(content, pos, hidden)
    }

    /// Registers a custom character for use with the screen. You can use [`macro@bitmap`] to
    /// create a character. Returns `None` if there is no free custom character slots left.
    pub fn register_custom_char(
        &mut self,
        bitmap: [u8; CHAR_HEIGHT],
    ) -> Result<Option<CustomCharacterRef>, D::Error> {
        let id = self.core.advance_id();
        if let Some((idx, slot)) = self.core.free_slot_mut() {
            self.lcd
                .set_custom_character_at(&mut self.delay, idx as u8, bitmap)?;
            Ok(Some(CustomCharacterRef(*slot.insert(id), idx)))
        } else {
            Ok(None)
        }
    }

    /// Unregisters an existing custom character.
    pub fn unregister_custom_char(
        &mut self,
        character: CustomCharacterRef,
    ) -> Result<(), D::Error> {
        if let Some((idx, slot)) = self.core.find_slot_mut(character) {
            self.lcd
                .set_custom_character_at(&mut self.delay, idx as u8, [0u8; CHAR_HEIGHT])?;
            *slot = None;
        }
        Ok(())
    }
    /// changes an existing custom character to a new bitmap, preserves its ID.
    pub fn reregister_custom_char(
        &mut self,
        old_character: CustomCharacterRef,
        new: [u8; CHAR_HEIGHT],
    ) -> Result<Option<CustomCharacterRef>, D::Error> {
        let id = self.core.advance_id();

        if let Some((idx, slot)) = self.core.find_slot_mut(old_character) {
            self.lcd
                .set_custom_character_at(&mut self.delay, idx as u8, new)?;
            Ok(Some(CustomCharacterRef(*slot.insert(id), idx)))
        } else {
            Ok(None)
        }
    }

    /// Queues a transition to run on the widget with the key `key`. The transitions will run
    /// sequentially.
    pub fn queue_transition(
        &mut self,
        key: u32,
        transition: Transition<S::Text>,
    ) -> Result<&mut Self, StorageError> {
        self.core.queue_transition(key, transition)?;
        Ok(self)
    }

    /// Ticks the UI and all of its widgets, then draws the current UI state to the screen.
    pub fn draw(&mut self) -> Result<(), UiError<D::Error>>
    where
        <D as LcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>>::Error: BackendError,
    {
        self.core.tick();

        let delay = &mut self.delay;
        let mut drawn_this_frame = S::Vec::new();
        for (_, elem) in self.core.meta.elems.iter() {
            if !elem.hidden {
                self.lcd.move_cursor(delay, elem.pos)?;
                match &elem.content {
                    WidgetContent::Text(ascii_string) => {
                        self.lcd.write_str(delay, ascii_string.chars())?;
                        drawn_this_frame.extend(
                            (elem.pos.x()..(elem.pos.x() + ascii_string.len() as u8))
                                .map(|x| ScreenCoordinates::at(x, elem.pos.y())),
                        );
                    }
                    WidgetContent::CustomCharacter(CustomCharacterRef(_, idx)) => {
                        self.lcd.write_custom_character(delay, *idx as u8)?;
                        drawn_this_frame.push(elem.pos)?;
                    }
                }
            }
        }

        for pixel in self
            .core
            .meta
            .last_frame_drawn
            .iter()
            .filter(|&x| !drawn_this_frame.contains(x))
        {
            self.lcd
                .move_cursor(delay, *pixel)?
                .write_byte(delay, b' ')?;
        }

        let drawn_this_frame = {
            let mut s = S::Set::new();
            s.extend(drawn_this_frame);
            s
        };
        self.core.meta.last_frame_drawn = drawn_this_frame;

        Ok(())
    }
}

#[cfg(feature = "async")]
impl<
    const CHAR_HEIGHT: usize,
    const CUSTOM_CHARACTER_SLOTS: usize,
    S: Storage,
    D: AsyncLcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>,
    Y: ADelay,
> AsyncLcdScreen<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS, S, D, Y>
{
    /// Initializes the screen UI.
    pub async fn new(mut lcd: D, mut delay: Y) -> Result<Self, D::Error> {
        lcd.prepare_screen(&mut delay)
            .await?
            .clear(&mut delay)
            .await?;

        Ok(AsyncLcdScreen {
            core: LcdScreenCore {
                meta: ScreenMetadata::default(),
                id_counter: 0,
            },
            lcd,
            delay,
        })
    }

    /// Creates a new widget on the screen.
    pub fn new_elem(
        &mut self,
        content: WidgetContent<S::Text>,
        pos: ScreenCoordinates,
        hidden: bool,
    ) -> Result<u32, StorageError> {
        self.core.new_elem(content, pos, hidden)
    }

    /// Registers a custom character for use with the screen. You can use [`macro@bitmap`] to
    /// create a character. Returns `None` if there is no free custom character slots left.
    pub async fn register_custom_char(
        &mut self,
        bitmap: [u8; CHAR_HEIGHT],
    ) -> Result<Option<CustomCharacterRef>, D::Error> {
        let id = self.core.advance_id();
        if let Some((idx, slot)) = self.core.free_slot_mut() {
            self.lcd
                .set_custom_character_at(&mut self.delay, idx as u8, bitmap)
                .await?;
            Ok(Some(CustomCharacterRef(*slot.insert(id), idx)))
        } else {
            Ok(None)
        }
    }

    /// Unregisters an existing custom character.
    pub async fn unregister_custom_char(
        &mut self,
        character: CustomCharacterRef,
    ) -> Result<(), D::Error> {
        if let Some((idx, slot)) = self.core.find_slot_mut(character) {
            self.lcd
                .set_custom_character_at(&mut self.delay, idx as u8, [0u8; CHAR_HEIGHT])
                .await?;
            *slot = None;
        }
        Ok(())
    }
    /// changes an existing custom character to a new bitmap, preserves its ID.
    pub async fn reregister_custom_char(
        &mut self,
        old_character: CustomCharacterRef,
        new: [u8; CHAR_HEIGHT],
    ) -> Result<Option<CustomCharacterRef>, D::Error> {
        let id = self.core.advance_id();

        if let Some((idx, slot)) = self.core.find_slot_mut(old_character) {
            self.lcd
                .set_custom_character_at(&mut self.delay, idx as u8, new)
                .await?;
            Ok(Some(CustomCharacterRef(*slot.insert(id), idx)))
        } else {
            Ok(None)
        }
    }

    /// Queues a transition to run on the widget with the key `key`. The transitions will run
    /// sequentially.
    pub fn queue_transition(
        &mut self,
        key: u32,
        transition: Transition<S::Text>,
    ) -> Result<&mut Self, StorageError> {
        self.core.queue_transition(key, transition)?;
        Ok(self)
    }

    /// Ticks the UI and all of its widgets, then draws the current UI state to the screen.
    pub async fn draw(&mut self) -> Result<(), UiError<D::Error>>
    where
        <D as AsyncLcdBackend<CHAR_HEIGHT, CUSTOM_CHARACTER_SLOTS>>::Error: BackendError,
    {
        self.core.tick();

        let delay = &mut self.delay;
        let mut drawn_this_frame = S::Vec::new();
        for (_, elem) in self.core.meta.elems.iter() {
            if !elem.hidden {
                self.lcd.move_cursor(delay, elem.pos).await?;
                match &elem.content {
                    WidgetContent::Text(ascii_string) => {
                        self.lcd.write_str(delay, ascii_string.chars()).await?;
                        drawn_this_frame.extend(
                            (elem.pos.x()..(elem.pos.x() + ascii_string.len() as u8))
                                .map(|x| ScreenCoordinates::at(x, elem.pos.y())),
                        );
                    }
                    WidgetContent::CustomCharacter(CustomCharacterRef(_, idx)) => {
                        self.lcd.write_custom_character(delay, *idx as u8).await?;
                        drawn_this_frame.push(elem.pos)?;
                    }
                }
            }
        }

        for pixel in self
            .core
            .meta
            .last_frame_drawn
            .iter()
            .filter(|&x| !drawn_this_frame.contains(x))
        {
            self.lcd
                .move_cursor(delay, *pixel)
                .await?
                .write_byte(delay, b' ')
                .await?;
        }

        let drawn_this_frame = {
            let mut s = S::Set::new();
            s.extend(drawn_this_frame);
            s
        };
        self.core.meta.last_frame_drawn = drawn_this_frame;

        Ok(())
    }
}
