//! Primary interface for high-level interactions with the screen.
// if someone has better descriptions for these @ me

pub mod transition;
pub mod widget;

#[cfg(not(feature = "alloc"))]
use heapless::{string::String, vec::Vec};

/// Helper macro to generate bitmap chaaracters, for use with the display and
/// [`crate::ui::widget::ScreenContent::CustomCharacter`].
///
///
/// DISCLAIMER: This macro is generated by an LLM. Claude Sonnet 4.6, specifically.
/// If you do not wish to use AI generated code, you can just declare a bitmap with an `u8` array.
///
/// Outside of this macro, this project contains no AI generated code.
#[macro_export]
macro_rules! bitmap {
    ($(($($bit:tt)+)),+ $(,)?) => {
        [$({ $crate::bitmap!(@row 0u8; $($bit)+) }),+]
    };

    (@row $($bit:tt)*) => {
        $crate::bitmap!(@acc $($bit)*)
    };

    (@acc $acc:expr;) => { $acc };
    (@acc $acc:expr; . $($rest:tt)*) => {
        $crate::bitmap!(@acc ($acc << 1); $($rest)*)
    };
    (@acc $acc:expr; # $($rest:tt)*) => {
        $crate::bitmap!(@acc ($acc << 1) | 1; $($rest)*)
    };
}

#[cfg(feature = "alloc")]
mod alloc_impl {
    use alloc::{collections::btree_set::BTreeSet, vec::Vec};

    #[cfg(feature = "async")]
    use crate::backend::AsyncLcdBackend;
    use crate::{backend::LcdBackend, ui::widget::ScreenElement};

    #[derive(Default, Debug)]
    struct ScreenMetadata {
        elems: Vec<(u32, ScreenElement)>,
        last_frame_drawn: BTreeSet<(u8, u8)>,
        custom_characters: [Option<u32>; 8], // idx -> screen character slot, u32 -> character id
    }

    /// The manager for all UI widgets. Blocking version.
    pub struct LcdScreen<const CHAR_HEIGHT: usize, D: LcdBackend<CHAR_HEIGHT>> {
        lcd: D,
        meta: ScreenMetadata,
    }

    /// The manager for all UI widgets. Async version.
    #[cfg(feature = "async")]
    pub struct AsyncLcdScreen<const CHAR_HEIGHT: usize, D: AsyncLcdBackend<CHAR_HEIGHT>> {
        lcd: D,
        meta: ScreenMetadata,
    }

    impl<const CHAR_HEIGHT: usize, D: LcdBackend<CHAR_HEIGHT>> LcdScreen<CHAR_HEIGHT, D> {}
    #[cfg(feature = "async")]
    impl<const CHAR_HEIGHT: usize, D: AsyncLcdBackend<CHAR_HEIGHT>> AsyncLcdScreen<CHAR_HEIGHT, D> {
        async fn new(mut lcd: D) -> Self {
            let delay = &mut embassy_time::Delay;

            LcdScreen {
                lcd,
                meta: ScreenMetadata::default(),
            }
        }

        async fn new_elem(&mut self, content: ScreenContent, pos: (u8, u8), hidden: bool) -> u32 {
            let screen_state = &mut self.meta;
            let id = RANDOM.get().await.random();
            screen_state.elems.push((
                id,
                ScreenElement {
                    content,
                    pos,
                    hidden,
                    transitions: VecDeque::new(),
                    transition_progress: None,
                },
            ));
            id
        }

        async fn register_custom_char(&mut self, bitmap: BitMap) -> Option<CustomCharacterRef> {
            let screen_state = &mut self.meta;
            let id = RANDOM.get().await.random();
            let delay = &mut embassy_time::Delay;
            let free_slot = screen_state
                .custom_characters
                .iter_mut()
                .enumerate()
                .find(|(_, x)| x.is_none());

            if let Some((idx, slot)) = free_slot {
                self.lcd.custom_char(delay, &bitmap, idx as u8).await;
                Some(CustomCharacterRef(*slot.insert(id), idx))
            } else {
                None
            }
        }
        async fn unregister_custom_char(&mut self, character: CustomCharacterRef) {
            let screen_state = &mut self.meta;
            let delay = &mut embassy_time::Delay;
            let slot = screen_state
                .custom_characters
                .iter_mut()
                .enumerate()
                .find(|(_, slot)| slot.is_some_and(|id| id == character.0));

            if let Some((idx, slot)) = slot {
                self.lcd
                    .custom_char(
                        delay,
                        &bitmap!(
                            (. . . . .),
                            (. . . . .),
                            (. . . . .),
                            (. . . . .),
                            (. . . . .),
                            (. . . . .),
                            (. . . . .),
                            (. . . . .),
                        ),
                        idx as u8,
                    )
                    .await;
                *slot = None;
            }
        }
        async fn reregister_custom_char(
            &mut self,
            old_character: CustomCharacterRef,
            new: BitMap,
        ) -> Option<CustomCharacterRef> {
            let screen_state = &mut self.meta;
            let id = RANDOM.get().await.random();
            let delay = &mut embassy_time::Delay;
            let slot = screen_state
                .custom_characters
                .iter_mut()
                .enumerate()
                .find(|(_, slot)| slot.is_some_and(|id| id == old_character.0));

            if let Some((idx, slot)) = slot {
                self.lcd.custom_char(delay, &new, idx as u8).await;
                Some(CustomCharacterRef(*slot.insert(id), idx))
            } else {
                None
            }
        }

        async fn queue_transition(&mut self, key: u32, transition: Transition) -> &mut Self {
            {
                let screen_state = &mut self.meta;
                let found = screen_state.elems.iter_mut().find(|(id, _)| *id == key);
                if let Some((_, elem)) = found {
                    elem.transitions.push_back(transition);
                    debug!("{elem:?}")
                } else {
                    error!("no elem with id {key}")
                }
            }
            self
        }

        async fn draw(&mut self) {
            let delay = &mut embassy_time::Delay;
            let screen_state = &mut self.meta;

            // run transitions
            screen_state.elems = screen_state
            .elems
            .drain(..)
            .filter_map(|(id, mut elem)| {
                match elem.transitions.front_mut() {
                    Some(Transition::Delete) => None,
                    rest => {
                        match rest {
                            Some(Transition::Hide) => {
                                elem.hidden = true;
                                elem.transitions.pop_front();
                            },
                            Some(Transition::Show) => {
                                elem.hidden = false;
                                elem.transitions.pop_front();
                            },
                            Some(Transition::ChangeTo(new)) => {
                                debug!("Transitioning {:?} into {new:?}", elem.content);
                                mem::swap(&mut elem.content, new);
                                elem.transitions.pop_front();
                            }
                            Some(&mut Transition::MoveTo { new, duration }) => {
                                let old = elem.pos;
                                _ = elem.transition_progress.insert(1);
                                debug!("Resolving move transition to {new:?}");
                                elem.transitions.pop_front();
                                elem.transitions
                                    .push_front(Transition::MoveToExt { old, new, duration });
                            }
                            Some(&mut Transition::MoveToExt { old, new, duration }) => {
                                let progress = elem.transition_progress.get_or_insert(0);
                                debug!(
                                    "Transitioning from {old:?} to {new:?}, {progress}/{duration} ticks passed"
                                );
                                let t = *progress as f32 / duration as f32;
                                let lerped_pos = (
                                    (old.0 as f32 + (new.0 as f32 - old.0 as f32) * t).round() as u8,
                                    (old.1 as f32 + (new.1 as f32 - old.1 as f32) * t).round() as u8,
                                );
                                elem.pos = lerped_pos;
                                if *progress < duration {
                                    *progress += 1;
                                } else {
                                    elem.transition_progress = None;
                                    elem.transitions.pop_front();
                                }
                            }
                            Some(&mut Transition::Wait { duration }) => {
                                let progress = elem.transition_progress.get_or_insert(0);
                                if *progress < duration {
                                    *progress += 1;
                                } else {
                                    elem.transition_progress = None;
                                    elem.transitions.pop_front();
                                }
                            }
                            _ => (),
                        }
                        Some((id, elem))
                    }
                }
            })
            .collect();

            let mut drawn_this_frame = Vec::new();
            for (_, elem) in &screen_state.elems {
                if !elem.hidden {
                    self.lcd
                        .set_cursor(delay, elem.pos.1 as usize, elem.pos.0)
                        .await;
                    match &elem.content {
                        ScreenContent::Text(ascii_string) => {
                            self.lcd.write(delay, Text(ascii_string.as_str())).await;
                            drawn_this_frame.extend(
                                (elem.pos.0..(elem.pos.0 + ascii_string.len() as u8))
                                    .map(|x| (x, elem.pos.1)),
                            );
                        }
                        ScreenContent::CustomCharacter(CustomCharacterRef(_, idx)) => {
                            self.lcd.write(delay, CustomChar(*idx as u8)).await;
                            drawn_this_frame.push(elem.pos);
                        }
                    }
                }
            }

            for pixel in screen_state
                .last_frame_drawn
                .iter()
                .filter(|&x| !drawn_this_frame.contains(x))
            {
                self.lcd
                    .set_cursor(delay, pixel.1 as usize, pixel.0)
                    .await
                    .write(delay, Text(" "))
                    .await;
            }

            let drawn_this_frame = {
                let mut s = BTreeSet::new();
                s.extend(drawn_this_frame);
                s
            };
            screen_state.last_frame_drawn = drawn_this_frame;
        }
    }
}

#[cfg(not(feature = "alloc"))]
mod heapless_impl {
    use heapless::{index_set::FnvIndexSet, vec::Vec};

    use crate::ui::widget::ScreenElement;

    #[derive(Default, Debug)]
    struct ScreenMetadata<
        const MAX_ELEMS: usize,
        const MAX_TRANSITIONS: usize,
        const STR_LEN: usize,
    > {
        elems: Vec<(u32, ScreenElement<MAX_TRANSITIONS, STR_LEN>), MAX_ELEMS>,
        last_frame_drawn: FnvIndexSet<(u8, u8)>,
        custom_characters: [Option<u32>; 8], // idx -> screen character slot, u32 -> character id
    }

    /// The manager for all UI widgets. Blocking version.
    pub struct LcdScreen<
        const CHAR_HEIGHT: usize,
        const MAX_ELEMS: usize,
        const MAX_TRANSITIONS: usize,
        const STR_LEN: usize,
        D: LcdBackend<CHAR_HEIGHT>,
    > {
        lcd: D,
        meta: ScreenMetadata<MAX_ELEMS, MAX_TRANSITIONS, STR_LEN>,
    }

    /// The manager for all UI widgets. Async version.
    #[cfg(feature = "async")]
    pub struct AsyncLcdScreen<
        const CHAR_HEIGHT: usize,
        const MAX_ELEMS: usize,
        const MAX_TRANSITIONS: usize,
        const STR_LEN: usize,
        D: AsyncLcdBackend<CHAR_HEIGHT>,
    > {
        lcd: D,
        meta: ScreenMetadata<MAX_ELEMS, MAX_TRANSITIONS, STR_LEN>,
    }

    impl<
        const CHAR_HEIGHT: usize,
        const MAX_ELEMS: usize,
        const MAX_TRANSITIONS: usize,
        const STR_LEN: usize,
        D: LcdBackend<CHAR_HEIGHT>,
    > LcdScreen<CHAR_HEIGHT, D>
    {
    }

    #[cfg(feature = "async")]
    impl<
        const CHAR_HEIGHT: usize,
        const MAX_ELEMS: usize,
        const MAX_TRANSITIONS: usize,
        const STR_LEN: usize,
        D: AsyncLcdBackend<CHAR_HEIGHT>,
    > AsyncLcdScreen<CHAR_HEIGHT, D>
    {
    }
}

#[cfg(feature = "alloc")]
pub use alloc_impl::*;
#[cfg(not(feature = "alloc"))]
pub use heapless_impl::*;
